version: "3.8"

services:
  flaskapp:
    container_name: flaskapp
    image: REGISTRY_LOGIN_SERVER/azure-container-group-with-flask-nginx_flaskapp:VERSION
    ports:
      - "5000:5000"
    build: 
      context: ./
      dockerfile: Dockerfile
  
  nginx:
    container_name: nginx
    image: REGISTRY_LOGIN_SERVER/azure-container-group-with-flask-nginx_nginx:VERSION
    ports:
      - "80:80"
    restart: always
    build: ./.nginx
    depends_on:
      - flaskapp